version: '3.7'

services:
    web_app:
        build: ./
        command: uvicorn app.main:app --host 0.0.0.0. --port 8000
        ports:
            - 8000:8000
        volumes:
            - ./:/app/

    db:
        image: 'mongo'
        environment:
            - MONGO_INITDB_DATABASE=mydb
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=1
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
            - ./mongo-volume:/data/db
        ports:
            - '27017-27019:27017-27019'